### ISSUE TITLE
TypeError: Cannot read property 'sys' of undefined

### ISSUE THREAD

**Issue by SMillerDev** [contentful-labs/contentful-space-sync#30]
I have this config file:
``` json
{
  "contentModelOnly": true,
  "sourceSpace": "12345678",
  "destinationSpace": "12345678",
  "sourceDeliveryToken": "12345678",
  "sourceManagementToken": "12345678",
  "destinationManagementToken": "12345678"
}
```

Which gives the following error:
```
sean@somepc:~$ contentful-space-sync --config config.json 
> Contentful Space Sync:
Let's sync some content across spaces! 
> No previous sync token found or fresh sync requested.
Synchronizing fresh content from 12345 to 12345 
> Getting content from source space 
ERR! Failed with
 TypeError: Cannot read property 'sys' of undefined
ERR! Failed with
     at new APIError (/usr/local/lib/node_modules/contentful-space-sync/node_modules/contentful-management/lib/api-error.js:10:20)
ERR! Failed with
     at /usr/local/lib/node_modules/contentful-space-sync/node_modules/contentful-management/index.js:128:13
ERR! Failed with
     at tryCatcher (/usr/local/lib/node_modules/contentful-space-sync/node_modules/questor/node_modules/bluebird/js/main/util.js:26:23)
ERR! Failed with
     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/contentful-space-sync/node_modules/questor/node_modules/bluebird/js/main/promise.js:507:31)
ERR! Failed with
     at Promise._settlePromiseAt (/usr/local/lib/node_modules/contentful-space-sync/node_modules/questor/node_modules/bluebird/js/main/promise.js:581:18)
ERR! Failed with
     at Promise._settlePromises (/usr/local/lib/node_modules/contentful-space-sync/node_modules/questor/node_modules/bluebird/js/main/promise.js:697:14)
ERR! Failed with
     at Async._drainQueue (/usr/local/lib/node_modules/contentful-space-sync/node_modules/questor/node_modules/bluebird/js/main/async.js:123:16)
ERR! Failed with
     at Async._drainQueues (/usr/local/lib/node_modules/contentful-space-sync/node_modules/questor/node_modules/bluebird/js/main/async.js:133:10)
ERR! Failed with
     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/contentful-space-sync/node_modules/questor/node_modules/bluebird/js/main/async.js:15:14)
ERR! Failed with
     at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! Failed with
  [TypeError: Cannot read property 'sys' of undefined]
```

Which seems to be an error in the library

**Comment by trodrigues** [comment]
Hi there,

would you mind trying version 2.1.1 and seeing if the output is any different? I've released an updated version of contentful-management which improves error handling and should give you a better idea of what the actual problem is in this case.

**Comment by SMillerDev** [comment]
Error is now: (not sure if it changed)

```
ERR! Failed with
 TypeError: Cannot read property 'sys' of undefined
ERR! Failed with
     at new APIError (/usr/local/lib/node_modules/contentful-space-sync/node_modules/contentful-management/lib/api-error.js:10:20)
ERR! Failed with
     at /usr/local/lib/node_modules/contentful-space-sync/node_modules/contentful-management/index.js:128:13
ERR! Failed with
     at tryCatcher (/usr/local/lib/node_modules/contentful-space-sync/node_modules/questor/node_modules/bluebird/js/main/util.js:26:23)
ERR! Failed with
     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/contentful-space-sync/node_modules/questor/node_modules/bluebird/js/main/promise.js:507:31)
ERR! Failed with
     at Promise._settlePromiseAt (/usr/local/lib/node_modules/contentful-space-sync/node_modules/questor/node_modules/bluebird/js/main/promise.js:581:18)
ERR! Failed with
     at Promise._settlePromises (/usr/local/lib/node_modules/contentful-space-sync/node_modules/questor/node_modules/bluebird/js/main/promise.js:697:14)
ERR! Failed with
     at Async._drainQueue (/usr/local/lib/node_modules/contentful-space-sync/node_modules/questor/node_modules/bluebird/js/main/async.js:123:16)
ERR! Failed with
     at Async._drainQueues (/usr/local/lib/node_modules/contentful-space-sync/node_modules/questor/node_modules/bluebird/js/main/async.js:133:10)
ERR! Failed with
     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/contentful-space-sync/node_modules/questor/node_modules/bluebird/js/main/async.js:15:14)
ERR! Failed with
     at processImmediate [as _immediateCallback] (timers.js:383:17)
ERR! Failed with
  [TypeError: Cannot read property 'sys' of undefined]
```

**Comment by trodrigues** [comment]
That seems to be the same. Can you force the installation of contentful-space-sync 2.1.1 with `npm install -g contentful-space-sync@2.1.1` ?

After that, check if the file /usr/local/lib/node_modules/contentful-space-sync/node_modules/contentful-management/package.json has a line `"version": "0.6.0"`

**Comment by SMillerDev** [comment]
I forced the update, this results in the following:
```
ERR! Failed with
 OperationalError
ERR! Failed with
     at BufferList.<anonymous> (/usr/local/lib/node_modules/contentful-space-sync/node_modules/questor/index.js:40:25)
ERR! Failed with
     at BufferList.end (/usr/local/lib/node_modules/contentful-space-sync/node_modules/bl/bl.js:75:10)
ERR! Failed with
     at IncomingMessage.onend (_stream_readable.js:490:10)
ERR! Failed with
     at IncomingMessage.g (events.js:260:16)
ERR! Failed with
     at emitNone (events.js:72:20)
ERR! Failed with
     at IncomingMessage.emit (events.js:166:7)
ERR! Failed with
     at endReadableNT (_stream_readable.js:905:12)
ERR! Failed with
     at doNTCallback2 (node.js:450:9)
ERR! Failed with
     at process._tickCallback (node.js:364:17)
ERR! Failed with
  { [OperationalError]
ERR! Failed with
   cause: '',
ERR! Failed with
   body: '',
ERR! Failed with
   headers: { 'content-length': '0', connection: 'Close' },
ERR! Failed with
   status: 502,
ERR! Failed with
   request: 
ERR! Failed with
    { method: 'GET',
ERR! Failed with
      uri: 'https://api.contentful.com:443/spaces/123456/entries?sys.id%5Bin%5D=IhzxcItOi2sOM0CK6uAkY%2C3C6FpCGAdOMciEU6MaOYqE%2C2w62rmGl7WugagUKiuyeq0%2C4RXLdEOfwsamceeiWKoE8I%2C3YYr9VlNPWYOk8i4EkuKoe%2C4Jc6IBfHUki08qyu28i44c%2C3Mcbmv2ZfWq2gagkMWYK0a%2C2P5iaMZW5G2co0is2meMko%2CEYJI1GeYWOUuUk0GqYecY%2C4Lr0B3mXq0E46kMqky0SCM%2C5H1mqdFrxuIgOEo4oIuyg8%2CK0OpLFcPi6WM6ieyMi8MC%2C3V4WsKOrkkaCOKEG8WIoAu%2C1ub27qLU0QQywy2s0mGO6a%2C4XmwmZMUyIIU2sck2wkMOy%2C53biRFHnYsEGOGGkmcgCaW%2C1aNnJbimmukS8IY8eiImuy%2CqVLMNDNahMmY6cWeMWS6k%2C564lCe54k02wsIOM2qcyOO%2C20pVHRLTriyauGsaK6CYkq%2C3rQLjRIWowia66kMiY4KOM%2C3qPGjs3zvySwwKoqaKYY2w%2C3d0MWdcuicwGAge4E4k2qU%2C5Tde8xQiYgA0mmy2wscS08%2C1VWedWELkkeWKSSy8a4Gq4%2C52mCFro3u8aaKoiCKOSg8A%2C4ks8juA7SEGamiIocgYi0w%2C2ZumIRJjpY4ayAOgOKqUCo%2C3uR00hDq8wsmc6CsI66IGg%2C5SJDMR94IMyKCukgScEi6g%2C24xyaqfsMAUmKgquCUsKcC%2CJf2oUrSLYYmw2GKMqQK8I%2C3caD3EmSGAQWqwAueMSc4y%2C34QOsUUyYgY8GEK6cagYQW%2C2Ll97DVFEceaUEueWQAeeQ%2C33FnKz6gR2Eo0SiA2yEOKc%2C7ol1HH2zleqsMM2CywqKmw%2CSiypGMqUsEueAO2e4aykg%2C1AJK9yn0LeOGG4IsgQWSGu%2C1EvlHZEgTaouKGqOkOmY6o%2C3qcjmcnLOgui4uicGuqmgC%2C1zTZnRp4GYY2syg6uQKW6C%2C5VTZfRS5Hiw4mucuu0UcW8%2C7ugvIDdmQE6UA2OKKWwomq%2C6ht0e0cjTigm8aSyIm2sae%2C7qsnamcQvK0WUE0Eogemu%2C45xfub7BocmUSumUKkkkmk%2C1Kkz7MIvGMIOgyaSAucMeE%2C1BzWj5qfBeYi462OwcMEQ6%2C38GcDp6SoU6ok2uEwkq8Ss%2C5KhXskc8CsgykeEw0EUASq%2C8mImMlW4EMK40EwO6Qguu%2C3vHICSkah2cYAouUGMesWE%2C6bAzegWVKoAYW0CQquSYkc%2C1Bq9lXZPwkgwAcYMgcsoe2%2C1BSGRQD6Ju8kYMoSWcCC4i%2C14iBOrTKHC0UuMsas4oU48%2C2h8XzWyCx6oCmMc42Siqao%2C4Np4TKBHLGoIQmI2qicSQY%2C3ui9rQUkasOkECAIGCuSsc%2C6JMCN2PKDYwuqqqaiUgI8s%2C4ZHlo3GXmguWsg2E2e8CMY%2C3xH9UYxpxKgq8OaekmE4Cg%2C5DqNJZNvtSay08KmgQsmuq%2C4ihVijg6OkSqSauEgm4suK%2C2yFXlcKJEESu82oCyACAAa%2C6mcIaDqGf6qeCysWUkam4o%2C1kHhqzTp7iYS4uqO08YauQ%2CoWP7sY69QO0qGUMeEGkuE%2C1Pmy5fHDYQsCQk8IWoOmWc%2C3jfUf78Fos6g86cCs8UWqK%2C41nLu1vy0UQGwYMCimCwiq%2C5YIHI1Og36cqIEQYKm8sgy%2C3waXfCKdv28I8aoamIE4eG%2C4IiuDzCXKoci2wK46I8uIm%2C4SmVNLEmLmUIao2oaaMGa%2C1rzdLeZPVi8YG6gIIiMYAg%2C3G3JBUJdNum8Wwccgc8AUW%2C14HtF804SqYKykYI4c4mOe%2C6OJA6zBGYogyyI8emYOucw%2C3mi0Nlx6ZW4KogkIE6OWAM%2C2kCon7Ipeow0K0g0WEe086%2C2GUqMcdCXYOcka20I4eMwm%2C4oQupSG1moYE0ScuKueima%2C6vc6kLFU5yeM8gsYkKueK2%2Ccfea7iE1DGw46KSIIkIM8%2CrxCX9i24vY2sGcIGwEakA%2C37YMmqw4dyOiOc4AqSa2ek%2Chg1Zj82x0c6uwiUwqwm88%2C3orQdYooqsamIiWSWmu4YY%2C6xJCRJUlq0wame4aUAewyO%2C5QsnS6DxZeSaYueUWCmu4e%2C47sGYzzekwkWAoKiCA8gsO%2C6mEJN8NOFyuO8m6Imw668I%2C3h9bqCtoUUUCcI42k0isCq%2C4i4pDVbWvCikIcceoE446i%2C53nJotV7NCeKOUK8wWOWEs%2C4A7F8Ud6A8qCMMC4QAao8k%2C1pnPKNV0p2IYIK6g0mkskY%2C5ME6IgdKQEgWmYWYkceKiQ%2C20VVHdDXPGeEikA2m2oUIy%2C52ZanSwMC4SeeY8Qea6isI%2CqHHBtELPfEEouqK6ausGe%2C7b9dZnkK5iKIW20Ce02S8u%2C4GoxqmIPjy8CoS6qK4IEqs%2C6PlFQkXnBSiwAaS22qiC2q%2C11slRzofn66gsQ24meic8s%2Ci4reDLZr8W8cOoeO0KiWE%2C2ewZGkzDOguyQqcy0aQQWO%2C2Y4IKEtTYQCU0gGQw4isKM%2C3s9WGHRiyISYWYcsayGMwk%2CztUOHidsnAWkmGaEk8EIc%2C3co3FrSc7eoS66oqCYC0iY%2C4uJWHirGkw8ugcieS4iIUG%2C6ldfqYc97GQKiUS0u8Ye4S%2C1crIorNTcMUuMsYEuk6QSa%2C1MvN5xmrfWc6qiiQaegOoa%2C7vpTcFR4KQwwIymuy4wyM2%2C5m0HZO4DC0uEIsOAwSoM0M%2C6RruOcsOYwwsu6e4EkOUk2%2C2OSxsrewIEA4mS2A6QqGkE%2C1GDqiRtj0oo2GGMI8maoeW%2C5Lzl5DABDGaeU0e4UiAAUc%2C2n8nu2cZUgAW0Qwyeo0IU4%2C4FTxxTZD4QukIUAYQ8Iw4u%2C5XaThtn2cocuG2oUkwGgYe%2C2T9ZA5TqascGEC8G8yUMM2%2C78siUVxNqoioMeyky8IeaK%2C6hiBiH6xkA0OWQKE2mKesa%2C67ZYPHUTfiUkoM62iqUUku%2CQxhz4kdDiKCSy8ME0So0I%2CXjvL7AR3mEGywSOKMMmKQ%2Ctp1jSWnmbmomWm4qqM2ka%2CUSjueY1F4GkGKmkcUWWqC%2C19SpCMAmAIUsU88Q880scG%2C6uDL8WsDZY644iIymOCk6U%2C1EPItusMA8YQAAsGUYugUS%2C1UH29roXYMCAC4mC86K4Sw%2C16aWOmOoEUMWIQgc4ik0oE%2C683doV5tGEKWuiiC2kkGSs%2Ctg8KSucJCokkKSaq0eC44%2CcJab2XeRe8Kw8s08EQs8k%2C5vgePCSTL2w4YkCY2KEUU6%2C4Moj0BfLzWgu6miQKmKYCW%2C2Lz75bCKVaqsUOMCQQKw2E%2C7uhqKZ1HMI8gWo6cokyIaq%2C6yjbF4YeUo6smqY8oqM6i2%2C4tCT0DZ0FqAwomWYq6Uii6%2C2WiMN1rjE4MI20OyyGUCYI%2Ck8eqtcktigY80UASmmo6G%2C6c4Dlx1JQIaIiQimQAawEi%2C2FTnchzmLuosYIos4SOkoQ%2C5v0fWz3ou44WGsqOiOasG8%2C42YYmmT6eIouYEOqssWQ0Y%2C5znWqI12sEmiIKqYqemUc0%2C6ADFiXNjc4YE4eoKOyiY80%2C5sGCXTzjQkCQKQYowsmuGA%2CCsWBgIzYkgGWQqIoU0Ymg%2C3ixzKJqS3YwSGMWgk88MmI%2C4N63SHgMI8UQaUCGIs6wEW%2C71YLBcdvhuiSKiAUc0602G%2C4QXtniHyikUwYumA6gwWuO%2C6irrJyIn5KMm4QYuaumWwS%2C69SVmsaisw2qaQo6SOWe4g%2C6dbvAMr3y0iIgAq6QwEWCY%2C4r1r3aExJeG0gAokYg6CIO%2C6CSDQqYMqAi8mQ2sgikYO0%2C4a07iPQct2kKoEcoIeQYEw%2C5cztaA1GRG6AUE8WoYogAQ%2C68XBNg1nagmoggaS6yKqWK%2C1UVVBwPYAQ6YSeWcUMSWao%2C1eZ02NUArOUUcGEQUKAwyy%2CkrU0Jo9G48kuysOOIm2m%2C3taLxU7H9CeuAAis0keIYi%2C5i6sAiYBcWOYIyoqicSqIa%2CRrlzLsua0EGeEcaAwYKac%2C3TRtN2h1p6ACGmsqS8s6aI%2C32AsXf2Gg0gMeYgwO8mQcq%2C3qMFk7BTdm2IoMO20WOGqs%2C2omYa7iFEEUQegO8ySEQc6%2C39Ppr4vEn6YoMAK6eMEGKk%2C2jnvFbD1fC6y40IUoMqsuW%2C3c5b5g63kkmueOiO8Awasy%2C7H3F8OqwKsIakICmum6uYy%2C5xL4bv8pwI2SSo6g6w4cq6%2C3ROP9Mjy6QO6i6SqAek2UY%2C6wrE6QL2g0C6m4c00gEKWE%2C6y3VJNU8Dewuk2CsO8WIGs%2Czs8b5PQSgo6KysiyisOow%2C1oOpKoCqCgS0MWM8iYWAYi%2C3y9kW2q2NOa0aOqQC8kUSK%2C4hbbh3svaUoaCus2koiCem%2C1maArAnoqQgyamymWyi6Is%2C4YvF2OYpZS22QWcqY868AG%2C6J1etn71Pa0MSqSkmaoC44%2CJwdHoV4XGUKkKCKIIgGq0%2C3js668cmiIWI6mOMUQmMIC%2C6n5OOB9VYWy406YgK0u26K%2C7hN9spX49G6GECsacwCGEk%2C27MVcZeataIgU0Y2AaWKEC%2C3WU5hPvNdKCEGEyaKm4MoO%2C3xeMusKGLeaOaIoaWagui0%2C7p9efKKN8WOA8AkMQmeuc4%2C3WQI01nIgU2aiyOsqmw8qE%2C1k4etnjp54Icsiko60eSyM%2C1GbSQkhBcQewicCgOYU8Eo%2C1Pbk4HqOt2y8ISg6Sc4oGk%2C2zsztpEmQA8uc2EW6U8W6K%2C1faw8Dc20KcIU2ie8wKUY0%2C514GYMohcIEYGeGey6i6ke%2C54sN3aOFSgGoeYoAWmw2gW%2C3dR5eO9nckyScyyIe6Aa2o%2C4WzVH5lhcc4aQs8a6wIqcA%2C5J6dVQfdzUoQ00KCEQMmEY%2C74nnczzJq8ewUqcyUyc268%2C4ySlo5gWo8sOyCOYYQmSAy%2C2FOe3TcVGoQuyuuCqoCUC6%2CvlwXMC4zVAkO60y4guSig%2CpPuMRlT4beG2aw6UYOiuY%2C38tXzOq3oIOUecqyWKwIam%2C2NumKqbCU0yQQY8Y2UamEs%2C5yMsMXOtQ4iyOyO4iiuSWa%2C2ai62L2gyE48WU2caWsKq8%2C39c1FswSDukSoSQ6gS6uiW%2C2d0Hh3A888c6gASQE8koom%2C3mws0McTqoYeKewCIcmk6e%2C2UHfh7XlKg4QCc0scYksKm%2C52a0PiirfGmAUEKA8uQoUk%2C4oUDGfbMyc2ggYU6IuEicw%2C6lyChXIlY4oAqIMEWo6GC2%2C2wkN09yddyWQOIaEk0osOU%2C27oTINcZkQuCQgiIKsGwOI%2C14syhAYDmGQMcYaSCKoKwE%2C1MCej1J10YgWeGIyaQ6eIc%2C5VAKP8da6ce08gm8cCuCEM%2C6ubWBeoYWkosYse6QWCQiE%2C3WJ24lZBIkOAWwwumWWUOG%2C4rNy7VHIjYUwMqoE8qEKGU%2C1LcSf37xNKiYmKQCQaYM0o%2CJ4mPlhq2MSeaos0aEI6W0%2C2lDrjchxZSMOKewiuOia8g%2CyG3w6jC9peM4ue2oWwQ8k%2C665Pj7nzz2aO0kEwi6m6qy%2Chskla3esMguKuO8U6MOoc%2C4CC4q5PIxGAI6Uso0mAOKw%2C34mRFsmGic4Gg6WOuCOCMU%2C3jI27TSEPmCqEwkgqokeMa%2C5sD2dlWhUWGiaGCIqQoWoS%2C3TxZRUdEAUc0YaMyOOicMK%2C2sjAhYlZzmSSEWEUgqAuu2%2C43MRVa9LVSOu82gwAQOq8w%2C2uIt9dwrc8kqqou4SMgySy%2C54BT0YCZCowq8WSakm2Us6%2C6E7RyoVJ3qc0CK4WMaQk0e%2C6kTLwbfCaAaI0yA20MsgQU%2C27RNrv8NBeIy8Amo2eAii6%2CBJZ7qJ96i4K2CauwKGmkG%2C18EST6bO5mSUimyiY08OQi%2C2S3e8ziws0eiuouo4u40c8%2C2XARpJKs0M2E4SGSQc8kyQ%2C1WNYnvwpqkAW8cC02uOwMI%2CnhmSFjdhgOOyCew4UOAM2%2C3TNQ0stmmkM6Eqmw6GigkQ%2C6Iq6WgFhq8oWIMK68SyAkS%2C72CXOlzNSwq6wQgiU2IiYw%2Cj1LLXbBKLY8UUCCuY80Ei%2C2MV9gJSD0sEewMKO2qOwgU%2C4boV1dqHq82EuQAqE8Wkmo%2C4qIYYbj6FWI2CeSYKc2Asg%2C5vyQVIh6G4QkQseISe04SS%2C2jyTfK7oQ00IME6Qk8AC2Y%2CpCjI0pqcmWqOocWEgq4iG%2C1AfznyvZE8GeOUgWssQS6Y%2C3uEYF13kRWOGcSKegsaUka%2C23dJ2TujiIA8W86Giu4U0m%2CYrDkxmUyaceEEMGUiImmo%2C1fVqJ8k1FO62AsccI0oOmi%2C2nS1AANWBe6AKeSqIAQWEO%2C4yt1VEfEzKukig0GmsScQg%2C2wUyzvVJzqwi4EWyaiiIga%2C20XQzS3hM0kuwQMYOgcSI6%2C399gNz5fDqy2seSMYok6QQ%2C5SH6RZCgWACucY4SU4OQa4%2C474TTYdoXeus2QewwoYM4g%2C6uwDfTE4wguiaCIcUaysS4%2C1CXpTw5nQgWug2CwQU4sIC%2C64z9DBMBqMcIS4SaUui6YS%2C6gpyOT1idUo0OmYiCeaYCu%2C2M7RzeFmY8YGesGWA4gWcM%2C5Q1nCG7NnikqM8eUIeisCm%2ClyCsTy2EtEaIyKUusaAky%2C6qi35PItOwaIcgg6A6aIo2%2C6rOAZHZJ60AaymCQgeceIS%2C2MqIPlKHRewecKYoo2o8oC%2C3WSiBALoE0GUuWMqgOkuEs%2C6yJ08qUA1iOyqg8y0QMuI8%2C230oJDPSgcSG6cceQqQiUC%2C5p5bBRrAKkYU8oEEiWYS8u%2C28E88IfMVK8MmMEKyiMGA8%2C5suA882uwEIuSkOiCmESwU%2C1fHfp9dKlQkYGSmMOEqCEs%2C5yVaQyQt44CQcgGW2CYqIK%2C5HR1SewNwcmu4o2UG2syaO%2C5X7xR2ks7ueoko2UCqQKI2%2C2W061cDOCs08M6U6siyMuk%2C5B9SOaAtdC0oSIMs2qsoWU%2C3tSPQlsabeoaCGgM6Ae6k4%2C5i2drpcYVyuqc66AUmoUmi%2C2ZoY1YIWUgcewww6yq06AG%2C5Sgstu32g0wUsk8mQ8eW04%2C13aS6CaTvS62mKKuoUUs04%2C1OQBjPsFTKAYge4owsUkMg%2C2NJEdyNdnaka2GKwIE6KOy%2C3tFsIHObviYcisUk8yuUow%2C2JkttozSx2YoqUYK4Ck8U0%2C4E0E3UnQ9y8OGMGMKKMAuc%2C2qxIB5xJjmouyuwSUwk2mI%2CwRPZ0dlP0cWQUQmsKyemM%2C6xZNXL3EfCUcSgCeCckiaI%2C6TLdSZdW8wQScIGEQiYQCm%2C2LClLady6cUoqsAA0mawkA%2C5pSxoHSv6gO0gCqm6QYyaE%2C4zT7lREbgksW2YsQ0iiQ48%2C6bqJvC4ImcqC0UCi2YoEA6%2C6MS1pPc3ZKKEAYCso4iUo4%2C6vYP1kLx16y4sUaGAEi2OG%2C2XcyJMkvBCIam4IS4EwKao%2C4mX4T8W3DyuOQAMGmcKwCs%2C2vQRnlN3O8IKuQomkKuyKK%2C5muJ72X3ocEsiiSSkKIquM%2C26mLDpr10kyOmGygQ6MGWq%2C7gidBUwcogyu2osC0IIqU%2CTw5jPgarYW60qMEA0g8mI%2C61GwuEWukMCWqgsWwgAgUk%2CNNgrmR2O0SMAQ2CQQymCa%2C6N6cuR6tBCKswMOO0MMgiy%2C5w9qLgTiJUo6KIoUWWEUQ2%2C2iM2wtKxFGSwWuwOEqCa8c%2C6g8rpVHjy06yC0YYwaES8S%2C5wlA4ilOH6GqqGUc260M2E%2CSnT8RWNvu66kEIiqKuWYy%2C6gzkwMgw1iI4s8CewAGG4e%2C1QYmBZFSY4kMSK2eag6KcK%2C5Z53R219ZKswCCAgyQmWq6%2C1R0M0Hoaj2Gqm6w6Cy6OAK%2C6eCjPz9i5UWaQWgaYOEaiq%2C3ZkI2RM0o8mYIC4WqEckqm%2C26Of8yHFWEY88OgakM4Uoc%2C549AHjZNks2Wu6OsigGkoy%2CBIxfv4cfUO0O0IsIIm0WW%2C3LobuNhWy4qkm8MsWKCa4w%2C1ZmNB3ylMUmIsuwQcuWeum%2CtcUElPWHugqIYAEGkwc8Y%2C1VbDegWLBu0muKeaGwEe6k%2C3ySaF8U8ysEoCI4WyyII0K&access_token=123456',
ERR! Failed with
      body: undefined } }
```

**Comment by trodrigues** [comment]
Ok, this is very helpful. Essentially what's happening here is that when you are synchronizing to a space where you've synchronized before, the script will try to check if any content already exists there to use the appropriate versions when updating.

However, the request for the existing content should be split in multiple requests due to limitations in the size of URLs accepted by servers. In this particular situation it looks like the requests aren't being split properly.

I'll investigate this and come up with a bugfix soon as this is a major issue.

Thank you for the report!

**Comment by trodrigues** [comment]
Hi there,

version 2.1.2 was just released which should fix this problem.

Let me know how it works out.

**Comment by SMillerDev** [comment]
It seems to work now (still can't sync but for different reasons)
